### ISSUE TITLE
Use the new PyVista sphinx directives for interactive plots in the documentation?

### ISSUE THREAD

**Issue by banesullivan** [MatthewFlamm/pyransame#133]
It'd be great to make the documentation examples interactive! I'll see if I can make some time to contribute this while on winter holiday

**Comment by MatthewFlamm** [comment]
Direct help or some pointers would be very much appreciated.  I see where the `DynamicScraper` is specified for `sphinx_gallery` in `pyvista` `conf.py`, but this package does not use this Sphinx plugin.  Is it required?  It seems to me that interactive is opt-out through specifying `force_static` yet there must be some opt-in mechanism I cannot find.

**Comment by banesullivan** [comment]
Its all done directly through the pyvista-plot directive nowm so no need for the new dynamic scraper (that's specific to sphinx-gallery)

**Comment by banesullivan** [comment]
If you want a specific plot to opt-out of the dynamic rendering, you can specify `force_static` in the directive options:

```rst
.. pyvista-plot::
   :force_static:
```
